- hosts: dut
  connection: local
  gather_facts: no
  vars:
    state: present
    snake_tag: snake
  roles:
    - ansible-nfvis
  tags:
    - facts
  tasks:
  - name: Get NFVIS facts
    nfvis_facts:
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
    register: nfvis_facts

  - debug:
      var: nfvis_facts

#  - set_fact:
#      snake_vnfs: "{{ nfvis_facts.deployments.deployment | selectattr('name', 'search', '^' + snake_tag + '-') | map(attribute='name') | list }}"

  - set_fact:
      search_string: "^{{ snake_tag }}-"

  - name: Add VNF to inventory
    add_host:
      name: "{{ item.name }}"
      ansible_port: "{{ item.vm_group[0].interfaces.interface[0].port_forwarding.port[0].external_port_range[0].start }}"
      ansible_host: "{{ ansible_host }}"
      groups: snake
    loop: "{{ nfvis_facts.deployments.deployment }}"
    when: item.name is search("^{{ snake_tag }}-")

- hosts: snake
  gather_facts: no
  tasks:
    - debug:
        msg: "Hostname: {{ inventory_hostname }}, Host: {{ ansible_host }}, Port: {{ ansible_port }}"

    - name: Wait for VNFs to boot (timeout 10min)
      wait_for:
        port: "{{ ansible_port }}"
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost