---
- name: Prep the control host
  hosts: control_host:test_host
  gather_facts: no
  tags:
    - control
  tasks:
    - name: Wait for VNFs to boot (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost

    - name: Copy .deb packages
      copy:
        src: "{{ item }}"
        dest: /tmp
      loop:
        - libiperf0_3.1.3-1_amd64.deb
        - iperf3_3.1.3-1_amd64.deb

    - name: Install .deb packages
      command: dpkg -i "/tmp/{{ item }}"
      become: yes
      loop:
        - libiperf0_3.1.3-1_amd64.deb
        - iperf3_3.1.3-1_amd64.deb
      register: dpkg

- name: Prep the test hosts
  hosts: control_host
  gather_facts: no
  tags:
    - test
  tasks:
    - name: Copy iperf systemd
      copy:
        src: iperf3.service
        dest: /etc/systemd/system
      become: yes

    - name: Make sure a service is running
      systemd:
        name: iperf3
        state: started
        enabled: yes
      become: yes
