all:
  hosts:
    localhost:
      ansible_python_interpreter: /Users/stevenca/Workspaces/nfvis-harness/nfvis-harness.venv/bin/python
    harness:
      ansible_host: 192.133.177.18
      nfvis_networks:
        test-wan:
          bridge: lan-br
          trunk: no
          vlan: 4000
        test-lan:
          bridge: lan-br
          trunk: no
          vlan: 4001
    dut:
      ansible_host: 192.133.177.26
      nfvis_networks:
        test-wan:
          bridge: wan-br
          trunk: no
          vlan: 4000
        test-lan:
          bridge: lan-br
          trunk: no
          vlan: 4001
      test-rtr:
  children:
    nfvis:
      hosts:
        dut:
      children:
        encs:
          hosts:
            harness:
    harness_hosts:
      hosts:
        test_rtr:
      children:
        control_host:
          hosts:
            control:
        test_host:
          hosts:
            host1:
    vnf:
      hosts:
        test-rtr:
        host1:
        control:
