ansible_host: "{{ hostvars['harness'].ansible_host }}"
ansible_port: 20011
ansible_user: ubuntu
interfaces:
  ens4:
    enabled: true
    ip:
      primary: 192.168.255.10/24
    routes:
      - network: 192.168.0.0/16
        gateway: 192.168.255.1