ansible_port: 20000
interfaces:
  GigabitEthernet2:
    enabled: true
    nat: outside
    ip:
      primary: 192.133.177.27/25
      gateway: 192.133.177.1
  GigabitEthernet3:
    enabled: true
    nat: inside
    ip:
      primary: 192.168.0.1/24

nat:
  - type: inside
    source: list
    list: nat
    interface: GigabitEthernet2
    overload: true

access_lists:
  - name: nat
    type: standard
    rules:
      - action: permit
        source: 192.168.0.0/16

router:
  ospf:
    id: 1
    router_id: 192.168.0.1
    networks:
      - network: 192.168.0.0/24
        area: 0
nfvis:
  name: "{{ inventory_hostname }}"
  host: "{{ hostvars['harness'].ansible_host }}"
  image: isrv
  flavor: isrv-small
  bootup_time: 600
  kpi_data: yes
  recovery_wait_time: 5
  interfaces:
    - network: int-mgmt-net
    - network: wan-net
    - network: test-wan
  port_forwarding:
    - proxy_port: "{{ ansible_port }}"
      source_bridge: 'MGMT'
  config_data:
    - dst: iosxe_config.txt
      data: "{{ lookup('template', 'ios/nfvis.j2') }}"